version: "3.9"
services:
  nginx:
    build:
      context: .
    container_name: "nginx"
    networks:
      - front
    ports:
      - "80:80"
    depends_on:
      - "script-server"

  script-server:
    image: bugy/script-server:1.17.0
    container_name: script-server
    ports:
      - "5000:5000"
    networks:
      - front
#         aliases:
#           - script-server
    volumes:
      - conf:/app/conf/conf
      - logs:/app/conf/logs
      - src:/app/src
      - temp:/app/temp
      - web:/app/web
#    depends_on:
#      - "nginx"
volumes:
  conf: {}
  logs: {}
  src: {}
  temp: {}
  web: {}
networks:
  front:
    driver: bridge
