version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: web
    ports:
      - "80:80"
  script-server:
    image: bugy/script-server:1.17.0
    container_name: script-server
    ports:
      - "5000:5000"
    volumes:
#      - conf.json:/app/conf/conf.json
      - runners:/app/conf/runners
      - scripts:/app/scripts
    depends_on:
      - "nginx"
volumes:
#  conf.json: {}
  runners: {}
  scripts: {}