---
# tasks file for docker_install
- name: update system
  apt: update_cache=yes force_apt_get=yes
  register: output

- debug:
    var: output

- name: install docker, docker-compose
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true