---
# tasks file for timesync

- name: Test date
  debug:
    msg: "{{ ansible_date_time }}"
- name: Set timezone
  timezone:
    name: Asia/Novosibirsk
- name: Install NTP
  apt: name=ntp update-cache=yes
