---
- name: update system
  apt: update_cache=yes force_apt_get=yes
  register: output

- debug:
    var: output
- name: install krb5-config, libnss-ldap
  apt: name={{ item }} state=latest
  loop:
    - krb5-config
    - libnss-ldap