---
# tasks file for script-server
- name: copy docker-compose.yaml
  copy:
    src: templates/{{ item }}
    dest: /root/app/
    owner: root
    group: root
    mode: 0644
  with_items:
    - docker-compose.yaml
    - nginx.conf
    - default.conf
    - Dockerfile
    - conf.json
- name: exit docker container
  docker_compose:
    project_src: app/
    state: absent
- name: docker-compose up
  docker_compose:
    project_src: app/
    state: present

